{
 "title": "JVM Metrics - Jolokia 2",
 "description": "This dashboard will provide JVM metrics for a Java application instrumented with Jolokia Agent.",
 "tags": [
  "InfluxDB",
  "Telegraf",
  "Jolokia",
  "JVM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Database", "query": "influxdb" },
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY = \"EC2_HOSTNAME\""
   },
   {
    "name": "IP",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY = \"EC2_IPADDRESS\" WHERE \"EC2_HOSTNAME\"=~/^$hostname$/"
   },
   {
    "name": "Interval",
    "query": "10s,,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview - $Server - $IP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "java_runtime",
     "select": [
      [
       { "params": [ "Uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  { "title": "JVM Stats - $Server - $IP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Heap Memory - Committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Heap Memory - Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Heap Memory - Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Non-Heap Memory - Committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Non-Heap Memory - Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Non-Heap Memory - Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Collection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "GC Collection Count - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_garbage_collector",
     "query": "SELECT difference(\"CollectionCount\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "GC Collection Time - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_garbage_collector",
     "query": "SELECT difference(\"CollectionTime\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool - Collection Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Collection Usage - Commited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Collection Usage - Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Collection Usage - Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool - Peak Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Peak Usage - Commited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Peak Usage - Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Peak Usage - Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool - Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage - Commited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "Usage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Usage - Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "Usage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Usage - Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_memory_pool",
     "select": [
      [
       { "params": [ "Usage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Daemon Thread Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Peak Thread Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Thread Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Class Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Loaded Class Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_class_loading",
     "select": [
      [
       { "params": [ "LoadedClassCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Unloaded Class Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "java_class_loading",
     "select": [
      [
       { "params": [ "UnloadedClassCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM - Last GC Info - $Server - $IP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Eden Space - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Eden Space - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.max\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Eden Space - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.used\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.used\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.used\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Survivor Space - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Survivor Space - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.max\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Survivor Space - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.used\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.used\", \"LastGcInfo.LastGcInfo.memoryUsageBeforeGc.Par Survivor Space.used\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageBeforeGc.Par Survivor Space.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    }
   ]
  },
  {
   "title": "Tenured Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Tenured - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Old Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS MarkSweep" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ConcurrentMarkSweep" }
     ]
    },
    {
     "alias": "$tag_name --- Tenured - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.max\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.max\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.max"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Old Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS MarkSweep" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ConcurrentMarkSweep" }
     ]
    },
    {
     "alias": "$tag_name --- Tenured - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.used\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.used\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.used\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Old Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS MarkSweep" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ConcurrentMarkSweep" }
     ]
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Metaspace - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_committed/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Metaspace.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_name --- Metaspace - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_max/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Metaspace.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_name --- Metaspace - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_used/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Metaspace.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Code Cache - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Code Cache - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.max\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Code Cache - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.used\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Code Cache.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name --- Compressed Class Space - Commited",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Compressed Class Space - Max",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.max\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.max"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_name --- Compressed Class Space - Used",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "java_last_garbage_collection",
     "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.used\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    }
   ]
  }
 ]
}